name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: pokemonfinderVite

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: pokemonfinderVite/package-lock.json

      - name: Install dependecies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test
